spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quiz
    username: root
    password: xiang123
server:
  port: 8080
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
